/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.parcticeform.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the form service. Represents a row in the &quot;practice_form&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.parcticeform.model.impl.formModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.parcticeform.model.impl.formImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see form
 * @generated
 */
@ProviderType
public interface formModel extends BaseModel<form> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a form model instance should use the {@link form} interface instead.
	 */

	/**
	 * Returns the primary key of this form.
	 *
	 * @return the primary key of this form
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this form.
	 *
	 * @param primaryKey the primary key of this form
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this form.
	 *
	 * @return the uuid of this form
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this form.
	 *
	 * @param uuid the uuid of this form
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the emp ID of this form.
	 *
	 * @return the emp ID of this form
	 */
	public long getEmpId();

	/**
	 * Sets the emp ID of this form.
	 *
	 * @param empId the emp ID of this form
	 */
	public void setEmpId(long empId);

	/**
	 * Returns the group ID of this form.
	 *
	 * @return the group ID of this form
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this form.
	 *
	 * @param groupId the group ID of this form
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the mobile no of this form.
	 *
	 * @return the mobile no of this form
	 */
	public long getMobileNo();

	/**
	 * Sets the mobile no of this form.
	 *
	 * @param mobileNo the mobile no of this form
	 */
	public void setMobileNo(long mobileNo);

	/**
	 * Returns the email of this form.
	 *
	 * @return the email of this form
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this form.
	 *
	 * @param email the email of this form
	 */
	public void setEmail(String email);

	/**
	 * Returns the user name of this form.
	 *
	 * @return the user name of this form
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this form.
	 *
	 * @param userName the user name of this form
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this form.
	 *
	 * @return the create date of this form
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this form.
	 *
	 * @param createDate the create date of this form
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this form.
	 *
	 * @return the modified date of this form
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this form.
	 *
	 * @param modifiedDate the modified date of this form
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the field1 of this form.
	 *
	 * @return the field1 of this form
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this form.
	 *
	 * @param field1 the field1 of this form
	 */
	public void setField1(String field1);

	/**
	 * Returns the field2 of this form.
	 *
	 * @return the field2 of this form
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this form is field2.
	 *
	 * @return <code>true</code> if this form is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this form is field2.
	 *
	 * @param field2 the field2 of this form
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this form.
	 *
	 * @return the field3 of this form
	 */
	public int getField3();

	/**
	 * Sets the field3 of this form.
	 *
	 * @param field3 the field3 of this form
	 */
	public void setField3(int field3);

	/**
	 * Returns the field4 of this form.
	 *
	 * @return the field4 of this form
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this form.
	 *
	 * @param field4 the field4 of this form
	 */
	public void setField4(Date field4);

	/**
	 * Returns the field5 of this form.
	 *
	 * @return the field5 of this form
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this form.
	 *
	 * @param field5 the field5 of this form
	 */
	public void setField5(String field5);

	@Override
	public form cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}